-- MySQL Script generated by MySQL Workbench
-- Wed Jul  1 20:19:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qt-gostoso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qt-gostoso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qt-gostoso` DEFAULT CHARACTER SET utf8 ;
USE `qt-gostoso` ;

-- -----------------------------------------------------
-- Table `qt-gostoso`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qt-gostoso`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qt-gostoso`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qt-gostoso`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qt-gostoso`.`table3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qt-gostoso`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qt-gostoso`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qt-gostoso`.`receita` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `conteudo` TEXT NOT NULL,
  `thumb` VARCHAR(150) NULL,
  `tags` VARCHAR(156) NOT NULL,
  `data_publicacao` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
